### ISSUE TITLE
Code Code Code !!!!!

### ISSUE THREAD

**Issue by SandLYJ** [ManiadisG/ExCB#1]
Your paper had recived by ECCV2024, can you realse your source code?

**Comment by ManiadisG** [comment]
Hello. My apologies for the delay! The code will be released this weekend along with model weights.

**Comment by SandLYJ** [comment]
No worries, thanks for your attention!

ManiadisG ***@***.***> 于2024年10月10日周四 16:29写道：

**Comment by ManiadisG** [comment]
Code & models uploaded. I will upload the kNN and semi-sup evaluations in the coming days, and I will also be doing cleanup and improving the documentation. Please let me know if you face any issues running the code.

**Comment by SandLYJ** [comment]
Thank you very much! It is vital for me!
